# Generated by Django 5.0.6 on 2024-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page_alter_catergory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Esta opção é necessária para publicar a página'),
        ),
    ]
