# Generated by Django 5.0.6 on 2024-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_page_options_post_imagespost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, max_length=11, null=True),
        ),
    ]
