# Generated by Django 5.0.6 on 2024-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_events_news_imageevent_imagenew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
