# Generated by Django 5.0.6 on 2024-06-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postattachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
    ]
