# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_commentsevents_commentsnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d'),
        ),
    ]
