from .index_views import *
from .post_view import *
from .page_view import *
from .event_view import *
from .new_view import *
from .category_view import *
from .shops_view import *
from .tag_view import *
from .search_view import *
from .create_user_view import *
from .edit_user_view import *
from .change_password_view import *
from .login_logout_view import *