# Generated by Django 5.0.6 on 2024-05-25 17:14

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='slide1',
            field=models.ImageField(blank=True, default='', upload_to='assets/slides/%Y/%m/%d/', validators=[utils.model_validators.validate_png]),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='slide2',
            field=models.ImageField(blank=True, default='', upload_to='assets/slides/%Y/%m/%d/', validators=[utils.model_validators.validate_png]),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/%d/', validators=[utils.model_validators.validate_png]),
        ),
    ]
