# Generated by Django 5.0.6 on 2024-05-25 17:15

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup_slide1_sitesetup_slide2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='slide3',
            field=models.ImageField(blank=True, default='', upload_to='assets/slides/%Y/%m/%d/', validators=[utils.model_validators.validate_png]),
        ),
    ]
