# Generated by Django 5.0.6 on 2024-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_sitesetup_slide3'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_carousel',
            field=models.BooleanField(default=True),
        ),
    ]
