# Generated by Django 5.0.6 on 2024-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_sitesetup_bairro_sitesetup_best_banner_sitesetup_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='best_banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='welcome_banner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
