# Generated by Django 5.0.6 on 2024-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0009_alter_sitesetup_best_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
