# Generated by Django 5.0.6 on 2024-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0010_alter_sitesetup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='operate_time_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='operate_time_shop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_operate_time',
            field=models.BooleanField(default=True),
        ),
    ]
