# Generated by Django 5.0.6 on 2024-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0011_sitesetup_operate_time_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='show_operate_time',
            new_name='show_operate_food',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_operate_shop',
            field=models.BooleanField(default=True),
        ),
    ]
