# Generated by Django 5.0.6 on 2024-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0012_rename_show_operate_time_sitesetup_show_operate_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_social',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
