# Generated by Django 5.0.6 on 2024-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0014_sitesetup_facebook_sitesetup_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
