# Generated by Django 5.0.6 on 2024-06-01 11:41

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0015_sitesetup_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='history_banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='img_history',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img_history/%Y/%m/%d', validators=[utils.model_validators.validate_png]),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='link_history_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_history_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='title_history_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
