# Generated by Django 5.0.6 on 2024-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0016_sitesetup_history_banner_sitesetup_img_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_login',
            field=models.BooleanField(default=True),
        ),
    ]
