# Generated by Django 5.0.6 on 2024-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0017_sitesetup_show_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
    ]
