# Generated by Django 5.0.6 on 2024-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0018_sitesetup_show_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_news',
            field=models.BooleanField(default=True),
        ),
    ]
