from django import forms
from django.core.exceptions import ValidationError
from site_setup.models import SiteSetup
from django_summernote.widgets import SummernoteWidget

class SiteSetupForm(forms.ModelForm):
    class Meta:
        model = SiteSetup
        fields = '__all__'
        widgets = {
            'show_title': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'title': forms.TextInput(attrs={'class':'form-control',}),
            'show_logo': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            # 'favicon': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),
            # 'logo': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),
            'show_location': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'endereco': forms.TextInput(attrs={'class':'form-control',}),
            'numero': forms.TextInput(attrs={'class':'form-control',}),
            'bairro': forms.TextInput(attrs={'class':'form-control',}),
            'cidade_estado': forms.TextInput(attrs={'class':'form-control',}),
            'cep': forms.TextInput(attrs={'class':'form-control',}),
            'show_description': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'description': SummernoteWidget(),
            'title_welcome_banner': forms.TextInput(attrs={'class':'form-control',}),
            'show_welcome_banner': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'welcome_banner': SummernoteWidget(),
            'title_best_banner': forms.TextInput(attrs={'class':'form-control',}),
            'show_best_banner': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'best_banner': SummernoteWidget(),
            'link_best_banner': forms.TextInput(attrs={'class':'form-control',}),
            'title_history_banner': forms.TextInput(attrs={'class':'form-control',}),
            'show_history_banner': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'history_banner': SummernoteWidget(),
            'link_history_banner': forms.TextInput(attrs={'class':'form-control',}),
            # 'img_history': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),
            'show_operate_shop': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'operate_time_shop': SummernoteWidget(),
            'show_operate_food': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'operate_time_food': SummernoteWidget(),
            'show_social': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'facebook': forms.TextInput(attrs={'class':'form-control',}),
            'instagram': forms.TextInput(attrs={'class':'form-control',}),
            'x_twitter': forms.TextInput(attrs={'class':'form-control',}),
            'youtube': forms.TextInput(attrs={'class':'form-control',}),
            'show_login': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_header': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_footer': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_search': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_menu': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_pagination': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_subscribe': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_comments': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_news': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_events': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'show_carousel': forms.CheckboxInput(attrs={'class':'form-check-input',}),
            'slide1_title': forms.TextInput(attrs={'class':'form-control',}),
            'slide2_title': forms.TextInput(attrs={'class':'form-control',}),
            'slide3_title': forms.TextInput(attrs={'class':'form-control',}),
            'slide1_description': forms.TextInput(attrs={'class':'form-control',}),
            'slide2_description': forms.TextInput(attrs={'class':'form-control',}),
            'slide3_description': forms.TextInput(attrs={'class':'form-control',}),
            # 'slide1': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),
            # 'slide2': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),
            # 'slide3': forms.FileInput(attrs={'class':'form-control', 'accept': 'image/*',}),

        }
        labels = {
            'show_title': 'Mostrar o título',
            'title': 'Título',
            'show_logo': 'Mostrar logo',
            'logo': 'Logo',
            'favicon': 'Ícone do navegador',
            'show_location': 'Mostrar endereço',
            'endereco': 'Endereço',
            'numero': 'Número',
            'bairro': 'Bairro',
            'cidade_estado': 'Cidade/Estado',
            'cep': 'CEP',
            'show_description': 'Slogan',
            'description': 'Descrição do site',
            'title_welcome_banner': 'Título do banner de boas vindas ao site',
            'show_welcome_banner': 'Mostra banner de boas vindas',
            'welcome_banner': 'Texto do banner de boas vindas',
            'title_best_banner': 'Título do banner de destaques',
            'show_best_banner': 'Mostrar banner de destaques',
            'best_banner': 'Texto do banner de destaques',
            'link_best_banner': 'Link externo para o banner de destaques',
            'title_history_banner': 'Título do banner de história',
            'show_history_banner': 'Mostrar banner de história',
            'history_banner': 'Texto do banner de história',
            'link_history_banner': 'Link externo do banner de história',
            'img_history': 'Imagem do banner de história',
            'show_operate_shop': 'Mostrar texto de atendimento das lojas',
            'operate_time_shop': 'Texto de atendimento das lojas',
            'show_operate_food': 'Mostrar texto de atendimento da alimentação',
            'operate_time_food': 'Texto de atendimento da alimentação',
            'show_social': 'Mostrar redes sociais do site',
            'facebook': 'Link do facebook do site',
            'instagram': 'Link do instagram do site',
            'x_twitter': 'Link do X do site',
            'youtube': 'Link do youtube do site',
            'show_login': 'Ver área de login',
            'show_header': 'Ver cabeçalho',
            'show_footer': 'Ver Rodapé',
            'show_search': 'Ver campos de busca das lojas',
            'show_menu': 'Ver menu principal',
            'show_pagination': 'Ver paginação',
            'show_subscribe': 'Ver inscrição do site',
            'show_comments': 'Ver comentários',
            'show_news': 'Ver novidades',
            'show_events': 'Ver eventos',
            'show_carousel': 'Ver carrossel de slides',
            'slide1_title': 'Título do slide 1',
            'slide2_title': 'Título do slide 2',
            'slide3_title': 'Título do slide 3',
            'slide1_description': 'Descrição do slide 1',
            'slide2_description': 'Descrição do slide 2',
            'slide3_description': 'Descrição do slide 3',
        }